# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
- task: Code Insight Scan@2
  inputs:
    URL: 'http://localhost:8888/codeinsight'
    Token: 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtbHVjZXJvIiwidXNlcklkIjoyLCJpYXQiOjE2MjE0NDUxOTV9.p95yo2Q_SDyPAnvz52K4Zy3OanHQyqHUd4topwrpHm_Lb1qRcUjbcXEVNZAoSbUW4B-4x7JDUeruI5RhBmGoSg'
    ProjectName: 'ePortal-Azure'
    Alias: 'eportal-azure'
    Host: 'eportal-azure'
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
